cmake,make-dist: build gperftools if WITH_STATIC_LIBSTDCXX
we could create a mini project to build a shared library, and use
try_compile() to test if the found gperftools is compiled with -fPIC.
but as we are targeting mostly xenial when enabling
WITH_STATIC_LIBSTDCXX, and google-perftools on xenial by default
is built without -fPIC. so let's keep it simple.

Signed-off-by: Kefu Chai <kchai@redhat.com>

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -61,6 +61,28 @@ download_boost() {
     rm -rf src/boost
 }
 
+download_gperftools() {
+    version=$1
+    shift
+    sha256=$1
+    shift
+    dname=gperftools-$gperftools_version
+    fname=$dir_name.tar.gz
+    url=https://github.com/gperftools/gperftools/releases/download/$dname/$fname
+
+    if ! wget -c --no-verbose -O $fname $url; then
+        echo "Download of $url failed"
+        exit 1
+    elif [ $(sha256sum $fname | awk '{print $1}') != $sha256 ]; then
+        echo "Error: failed to download gperftools: SHA256 mismatch."
+        exit 1
+    fi
+    tar xzf $fname -C src
+    mv src/$dname src/gperftools
+    tar cf ${outfile}.gperftools.tar ${outfile}/src/gperftools
+    rm -rf src/gperftools
+}
+
 _python_autoselect() {
   python_command=
   for interpreter in python2.7 python3 ; do
@@ -138,6 +160,7 @@ download_boost $boost_version 2684c972994ee57fc5632e03bf044746f6eb45d4920c343937
 build_dashboard_frontend
 tar --concatenate -f $outfile.all.tar $outfile.version.tar
 tar --concatenate -f $outfile.all.tar $outfile.boost.tar
+tar --concatenate -f $outfile.all.tar $outfile.gperftools.tar
 tar --concatenate -f $outfile.all.tar $outfile.tar
 tar --concatenate -f $outfile.all.tar dashboard_frontend.tar
 mv $outfile.all.tar $outfile.tar
